name: Build Metabase Firebolt Driver

on:
  workflow_dispatch:
    inputs:
      metabase-version:
        description: 'Metabase version'
        required: false
        type: string
        default: 'v0.48.0'
  workflow_call:
    inputs:
      metabase-version:
        description: 'Metabase version'
        required: true
        type: string
      branch:
        description: 'Branch to build'
        required: false
        type: string
        default: 'develop'
    outputs:
      jar-name:
        description: Firebolt Driver jar
        value: ${{ jobs.build-driver.outputs.jar-name }}
      version:
        description: Firebolt Driver version
        value: ${{ jobs.build-driver.outputs.version }}

jobs:
  build-driver:
    runs-on: ubuntu-latest
    outputs:
      jar-name: ${{ steps.package.outputs.jar-name }}
      version: ${{ steps.package.outputs.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch || 'develop' }}

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.7
        with:
          lein: '2.9.10'

      - name: "Install dependencies"
        run: |
          METABASE_VERSION=${{ github.event.inputs.metabase-version || 'v0.48.0' }} lein get-metabase-core
          lein deps

      - name: "Package into a jar"
        id: package
        run: |
          LEIN_SNAPSHOTS_IN_RELEASE=true DEBUG=1 lein uberjar
          echo "version=$(lein project-version | tail -1)" >> "${GITHUB_OUTPUT}"
          echo "jar-name=$(lein file-name | tail -1)" >> "${GITHUB_OUTPUT}"

      - name: Upload resulting jar file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.jar-name }}
          path: target/uberjar/${{ steps.package.outputs.jar-name }}
