name: Run integration tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Metabase Code"
        uses: actions/checkout@v2
        with:
          repository: metabase/metabase
          ref: "v0.44.0"

      - name: Checkout firebolt connector code
        uses: actions/checkout@v2
        with:
          path: modules/drivers/firebolt

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.7
        with:
          # Install just one or all simultaneously
          cli: '1.11.1.1155' # Clojure CLI based on tools.deps
          lein: '2.9.10'     # or use 'latest' to always provision latest version of leiningen

      - name: "Build metabase"
        shell: bash
        run: |
              clojure -X:deps prep
              cd modules/drivers
              clojure -X:deps prep
              cd ../..

      - name: Add firebolt driver imports to metabase
        shell: bash
        run: |
              sed --in-place '2s#$#\n  metabase/firebolt           {:local/root "firebolt"}#' modules/drivers/deps.edn
              sed --in-place '264s#$#\n    "modules/drivers/firebolt/test"#' deps.edn
              sed --in-place '299s#$#\n                                 "modules/drivers/firebolt/src"#' deps.edn
              sed --in-place 's/api.app.firebolt.io/api.staging.firebolt.io/'  modules/drivers/firebolt/src/metabase/driver/firebolt.clj
              sed --in-place '$ s/.$//' modules/drivers/deps.edn
              sed --in-place '$ a   :mvn/repos {"repsy" {:url "https://repo.repsy.io/mvn/firebolt/maven"}}}' modules/drivers/deps.edn
              sed --in-place '2s#$#\n :mvn/repos {"repsy" {:url "https://repo.repsy.io/mvn/firebolt/maven"}}#' bin/build-drivers/deps.edn
              sed --in-place '2s#$#\n :mvn/repos {"repsy" {:url "https://repo.repsy.io/mvn/firebolt/maven"}}#' bin/build-mb/deps.edn
              sed --in-place '2s#$#\n :mvn/repos {"repsy" {:url "https://repo.repsy.io/mvn/firebolt/maven"}}#' bin/release/deps.edn
              sed --in-place '152s#$#\n :mvn/repos {"repsy" {:url "https://repo.repsy.io/mvn/firebolt/maven"}}#' deps.edn
              yarn build-static-viz

      - name: Setup database and engine
        id: setup
        uses: firebolt-db/integration-testing-setup@master
        with:
          firebolt-username: ${{ secrets.FIREBOLT_USERNAME }}
          firebolt-password: ${{ secrets.FIREBOLT_PASSWORD }}
          api-endpoint: "api.staging.firebolt.io"
          region: "us-east-1"

      - name: Run metabase integration tests
        shell: bash
        run: |
              DRIVERS=firebolt MB_FIREBOLT_TEST_HOST=api.staging.firebolt.io MB_FIREBOLT_TEST_PORT=8123 MB_FIREBOLT_TEST_USER=${{ secrets.FIREBOLT_USERNAME }} MB_FIREBOLT_TEST_PASSWORD="${{ secrets.FIREBOLT_PASSWORD }}" MB_FIREBOLT_TEST_DB=metabase_test MB_FIREBOLT_TEST_ADDITIONAL_OPTIONS=engine=metabase_test_general_purpose clojure -X:dev:drivers:drivers-dev:test :only metabase.pulse-test
