name: Lint Clojure
on: [pull_request]
jobs:
  clj-kondo:
    name: runner / clj-kondo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: clj-kondo
        uses: nnichols/clojure-lint-action@v11
        with:
          reporter: github-pr-review
          github_token: ${{ secrets.GITHUB_TOKEN }}
