name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name to publish'
        required: true
      metabase-version:
        description: 'Metabase version'
        required: false
        type: string
        default: 'v0.48.0'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name || github.event.inputs.tag_name || 'develop' }}

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.7
        with:
          lein: '2.9.10'

      - name: "Install dependencies"
        run: |
          METABASE_VERSION=${{ github.event.inputs.metabase-version || 'v0.48.0' }} lein get-metabase-core
          lein deps

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GRADLE_SIGNING_KEY }}
          passphrase: ${{ secrets.GRADLE_SIGNING_PASSWORD }}

      - name: "Maven deploy"
        id: deploy
        env:
          SIGN_KEY_ID: ${{ steps.import_gpg.outputs.keyid }}
          MAVEN_REPO_USERNAME: ${{ secrets.MAVEN_REPO_USERNAME }}
          MAVEN_REPO_PASSWORD: ${{ secrets.MAVEN_REPO_PASSWORD }}
        run: |
          DEBUG=1 lein deploy-uberjar
          echo "version=$(lein project-version | tail -1)" >> "${GITHUB_OUTPUT}"
          echo "jar-name=$(lein file-name | tail -1)" >> "${GITHUB_OUTPUT}"


      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: target/${{ steps.deploy.outputs.jar-name }}
          tags: true
          draft: false

      - name: Upload resulting jar file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.deploy.outputs.jar-name }}
          path: target/${{ steps.deploy.outputs.jar-name }}
