name: Release

on:
  release:
    types: [published]

jobs:
  build-metabase:
    uses: ./.github/workflows/build-metabase.yml
    with:
      version: v0.44.0
  build-driver:
    uses: ./.github/workflows/build-driver.yml
    needs: build-metabase
  publish:
    runs-on: ubuntu-latest
    needs: [build-metabase, build-driver]
    steps:
      - name: Download jar file
        uses: actions/download-artifact@v2
        with:
          name: ${{ needs.build-driver.outputs.jar-name }}
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ needs.build-driver.outputs.jar-name }}
          tags: true
          draft: false
