name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name to publish'
        required: true
      metabase-version:
        description: 'Metabase version'
        required: false
        type: string
        default: 'v0.48.0'

jobs:
  build-driver:
    uses: ./.github/workflows/build-driver.yml
    with:
      metabase-version: ${{ github.event.inputs.metabase-version || 'v0.48.0' }}
      branch: ${{ github.event.release.tag_name || github.event.inputs.tag_name }}
  publish:
    runs-on: ubuntu-latest
    needs: [build-driver]
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: 'pom.xml'
          sparse-checkout-cone-mode: false
      - name: Download jar file
        uses: actions/download-artifact@v4.1.7
        with:
          name: ${{ needs.build-driver.outputs.jar-name }}
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ needs.build-driver.outputs.jar-name }}
          tags: true
          draft: false
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: >
            [
              {
                "id": "sonatype-nexus-staging",
                "username": "${{ secrets.MAVEN_REPO_USERNAME }}",
                "password": "${{ secrets.MAVEN_REPO_PASSWORD }}"
              }
            ]
      - name: "Maven deploy"
        run: |
          mvn deploy:deploy-file -Durl=https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/ \
                       -DpomFile=pom.xml \
                       -DrepositoryId=sonatype-nexus-staging \
                       -Dversion=${{ needs.build-driver.outputs.version }} \
                       -Dfile=${{ needs.build-driver.outputs.jar-name }} \
                       -Dsonatype-nexus-stagingUsername=${{ secrets.MAVEN_REPO_USERNAME }} \
                       -Dsonatype-nexus-stagingPassword=${{ secrets.MAVEN_REPO_PASSWORD }} \
                       -Dgpg.keyname=${{ secrets.GRADLE_SIGNING_KEY }} \
                       -Dgpg.passphrase=${{ secrets.GRADLE_SIGNING_PASSWORD }} \
