name: Release new version

on:
  release:
    types: [published]

jobs:
  build:
    uses: firebolt-db/metabase-firebolt-driver/.github/workflows/build-driver.yml@feature/jdbc-version-upgrade-v2

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Download jar file
        uses: actions/download-artifact@v2
        with:
          name: ${{ needs.build.outputs.jar-name }}
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ needs.build.outputs.jar-name }}
          tags: true
          draft: false
