name: Release

on:
  release:
    types: [published]

jobs:
  build-driver:
    uses: ./.github/workflows/build-driver.yml
  publish:
    runs-on: ubuntu-latest
    needs: build-driver
    steps:
      - name: Download jar file
        uses: actions/download-artifact@v2
        with:
          name: ${{ needs.build-driver.outputs.jar-name }}
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ needs.build-driver.outputs.jar-name }}
          tags: true
          draft: false
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: >
            [
              {
                "id": "firebolt",
                "username": "${{ secrets.REPSY_USERNAME }}" ,
                "password": "${{ secrets.REPSY_PASSWORD }}"
              }
            ]
      - name: "Maven deploy"
        run: |
          mvn deploy:deploy-file -Durl=https://repo.repsy.io/mvn/firebolt/maven \
                       -DgroupId=metabase \
                       -DartifactId=firebolt-driver \
                       -Dversion=${{ needs.build-driver.outputs.version }} \
                       -Dpackaging=jar \
                       -Dfile=${{ needs.build-driver.outputs.jar-name }} \
                       -DrepositoryId=firebolt
