name: Clojure CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: "Checkout Metabase Code"
      uses: actions/checkout@v2
      with:
        repository: metabase/metabase
        path: metabase

    - name: "Build metabase"
      run: |
            cd metabase
            clojure -X:deps prep
            cd modules/drivers
            clojure -X:deps prep
            cd ../..
            clojure -T:build uberjar
            cp metabase.jar ../
            
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
