name: Clojure CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: "build jar"
      uses: firebolt-db/metabase-firebolt-driver/.github/workflows/build.yml@security-scan
      
    - name: "Run FOSSA Scan"
      uses: fossas/fossa-action@v1
      with:
        api-key: ${{ secrets.FOSSA_TOKEN }}

    - name: "Run FOSSA Test"
      uses: fossas/fossa-action@v1
      with:
        api-key: ${{ secrets.FOSSA_TOKEN }}
        run-tests: true 
