name: Firebolt Security Scan

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2
      - name: "Run FOSSA Scan"
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ inputs.fossa-key }}
      - name: "Run FOSSA Test"
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ inputs.fossa-key }}
          run-tests: true