name: Build all and Scan

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-driver:
    uses: ./.github/workflows/build-driver.yml
    with:
      metabase-version: v0.46.1

  security-scan:
    needs: build-driver
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Fossa branch fix"
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        git fetch
        git branch --track ${GITHUB_HEAD_REF##*/} origin/${GITHUB_HEAD_REF##*/}
        git checkout ${GITHUB_HEAD_REF##*/}
    - name: "Run FOSSA Scan"
      uses: fossas/fossa-action@v1
      with:
        api-key: ${{ secrets.FOSSA_TOKEN }}
    - name: "Run FOSSA Test"
      uses: fossas/fossa-action@v1
      with:
        api-key: ${{ secrets.FOSSA_TOKEN }}
        run-tests: true
